name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  buildImage:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: |
        docker login -u="mchirico" -p=${{ secrets.DOCKER }} quay.io
        make
        make build2

    - name: Push the Docker image
      run: |
        docker push quay.io/mchirico/kind
        docker push quay.io/mchirico/ubuntu

