name: Schedule

on:
  schedule:
  - cron: '* * * 1 1'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker login -u="mchirico" -p=${{ secrets.DOCKER }} quay.io
        make
        docker push quay.io/mchirico/kind

